site_name: A

extra_css:
  - media/extra.css

copyright: ARGO

extra:
  generator: false

  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/davideriboli/A
    - icon: fontawesome/brands/centos 
      link: https://arg.ooo

theme:
  name: 'material'

  language: it

  logo: /Media/Immagini/logo.png

  favicon: Media/Immagini/favicon.png

  features:
    - navigation.indexes
    - navigation.top
    - header.autohide

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode ON

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
       icon: material/toggle-switch
       name: Light Mode ON
  
  font:
    text: Fira Sans Regular
    code: Fira Mono Regular

  markdown_extensions:
    - footnotes
    - toc:
        toc_depth: 0

  plugins:
    - search
    - roamlinks 